# Uses <https://github.com/marketplace/actions/continuous-benchmark>
name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-benchmark-v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --bench criterion --all-features --no-run

  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-benchmark-v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run benchmark
        run: |
          # Run criterion with bencher compatible output
          # Note: github-action-benchmark requires benchmark names to be identifiers.
          #       (i.e. they can not contain whitespace).
          # See <https://github.com/rhysd/github-action-benchmark/blob/a1914d7d/src/extract.ts#L181>
          cargo bench --bench criterion --all-features -- --noplot --output-format bencher | tee output.txt
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '30%'
          fail-on-alert: false
          comment-always: true
          comment-on-alert: false
          alert-comment-cc-users: '@recmo'
